title: Your awesome title
theme: minima
author: Piet Stam
email: pjastam@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is an awesome description of my new project site at GitHub.

# social links
twitter_username: pjastam # DO NOT include the @ character, or else the build will fail!
github_username: pjastam # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
